FollowPath:
  plugin: nav2_mppi_controller::MPPIController
  time_steps: 56
  model_dt: 0.05
  batch_size: 2000
  vx_std: 0.3
  vy_std: 0.0
  wz_std: 0.5
  vx_max: 0.5
  vx_min: 0.0
  vy_max: 0.0
  wz_max: 1.5
  iteration_count: 1
  prune_distance: 1.7
  transform_tolerance: 0.1
  temperature: 0.3
  gamma: 0.015
  motion_model: DiffDrive
  visualize: true
  critics: ["ConstraintCritic", "ObstaclesCritic", "GoalCritic", "GoalAngleCritic",
            "PathAlignCritic", "PathFollowCritic", "PathAngleCritic",
            "PreferForwardCritic"]
  ConstraintCritic:    {enabled: true, cost_power: 1, cost_weight: 4.0}
  ObstaclesCritic:     {enabled: true, cost_power: 1, cost_weight: 4.0, repulsion_weight: 1.5, critical_weight: 40.0, consider_footprint: false, collision_cost: 10000.0, collision_margin_distance: 0.2, near_goal_distance: 0.5}
  GoalCritic:          {enabled: true, cost_power: 1, cost_weight: 5.0, threshold_to_consider: 1.0}
  GoalAngleCritic:     {enabled: true, cost_power: 1, cost_weight: 3.0, threshold_to_consider: 0.4}
  PathAlignCritic:     {enabled: true, cost_power: 1, cost_weight: 14.0, max_path_occupancy_ratio: 0.05, trajectory_point_step: 3, threshold_to_consider: 0.4}
  PathFollowCritic:    {enabled: true, cost_power: 1, cost_weight: 4.0, offset_from_furthest: 5}
  PathAngleCritic:     {enabled: true, cost_power: 1, cost_weight: 2.0, offset_from_furthest: 4, threshold_to_consider: 0.4}
  PreferForwardCritic: {enabled: true, cost_power: 1, cost_weight: 5.0, threshold_to_consider: 0.4}
