#!/usr/bin/env python3
"""Dynamic scenarios for the 9 m arena, one per failure mode worth separating.

The arena's geometry does the work: a divider at y = 4.2 with two 1.4 m gaps.
Each gap is passable by the 0.30 m robot alone but NOT alongside a 0.25 m mover,
which needs 0.93 m of width. So a mover in a gap does not deadlock anything --
it moves the answer to the other gap, which is a homotopy decision rather than a
local dodge, and the left gap costs distance and passes an unknown static
cylinder, so taking it has to be worth something.

Scenarios
---------
none      no movers at all. The control: whatever the arena costs on geometry
          and unknown statics alone, before any dynamic avoidance is asked for.
crossing  a mover sweeping ACROSS the lower room, met head-on but with room to
          either side. The case constant-velocity prediction is actually valid
          for, which has never been isolated in the big room.
gapblock  a mover patrolling the RIGHT gap -- the direct route. Passing it in
          the gap is geometrically impossible, so the only answers are to wait
          or to take the left gap. Tests whether anything in the stack can make
          that choice, and what it costs.
corridor  a mover sweeping ALONG the approach to the right gap, i.e. down the
          robot's own direction of travel. This is the pathological geometry
          from the big room (43.5 s, 26% of a run, 4x the backing, 65% of the
          reversals) reproduced in 45 s instead of 170.
converge  two movers arriving at the same stretch from opposite sides. The
          multi-obstacle path, which the big room exercised in 0.09% of frames.
overtake  a slow mover going the SAME way through the right gap. _blocking
          needs fx > 0, so this is the geometry the detour never targeted.
parked    a mover with speed 0 sitting past the right gap: a pure test of the
          static/dynamic split, the thing that left a pillar unowned.

    python3 src/ammr_bringup/scripts/generate_arena_scenarios.py
"""
from pathlib import Path

ROOT = Path(__file__).resolve().parents[1]
DIVIDER_Y = 4.2
LEFT_GAP, RIGHT_GAP = 2.3, 5.9        # gap centres


def ob(name, a, b, speed):
    return (f'  - name:   {name}\n'
            f'    start:  [{a[0]:.2f}, {a[1]:.2f}]\n'
            f'    end:    [{b[0]:.2f}, {b[1]:.2f}]\n'
            f'    speed:  {speed}\n'
            f'    radius: 0.25\n'
            f'    height: 1.0\n')


def write(name, body, note):
    f = ROOT / 'config' / f'dynamic_trajectories_arena_{name}.yaml'
    f.write_text(f'# {note}\n#\n# Arena scenario, generated by\n'
                 f'# src/ammr_bringup/scripts/generate_arena_scenarios.py\n'
                 f'# Run with:  ARENA=1 TRAJ=arena_{name}\n\n'
                 f'dynamic_obstacles:\n\n{body}')
    print(f'  dynamic_trajectories_arena_{name}.yaml'
          f'{"" if body else "   (no movers)"}')


def main():
    print('arena scenarios:')

    write('none', '',
          'No movers: the cost of geometry and unknown statics alone.')

    # across the lower room, met head-on with room to both sides
    write('crossing',
          ob('dyn_obs_0', (1.2, 1.8), (7.6, 1.8), 0.30),
          'Mover crossing the lower room -- constant-velocity prediction valid, '
          'room to pass on either side.')

    # patrolling the direct (right) gap: cannot be passed there
    write('gapblock',
          ob('dyn_obs_0', (RIGHT_GAP, DIVIDER_Y - 0.9), (RIGHT_GAP, DIVIDER_Y + 0.9), 0.22),
          'Mover patrolling the RIGHT gap. The gap is too narrow to pass it, so '
          'the answers are to wait or to re-route through the left gap.')

    # sweeping along the robot's own direction of travel into the right gap
    write('corridor',
          ob('dyn_obs_0', (RIGHT_GAP, 1.6), (RIGHT_GAP, 3.9), 0.15),
          'Mover sweeping ALONG the approach to the right gap: the shared-'
          'corridor geometry, where there is nothing to go around.')

    # two movers, opposite sides, same stretch
    write('converge',
          ob('dyn_obs_0', (1.2, 1.8), (7.6, 1.8), 0.28) +
          ob('dyn_obs_1', (7.6, 6.8), (1.2, 6.8), 0.28),
          'Two movers meeting the robot on both sides of the divider -- the '
          'multi-obstacle path, exercised in 0.09% of frames so far.')

    # slower mover going the same way through the right gap
    write('overtake',
          ob('dyn_obs_0', (RIGHT_GAP, 2.2), (RIGHT_GAP, 6.4), 0.10),
          'A slower mover going the SAME way through the right gap: _blocking '
          'requires fx > 0, so the detour was never designed for this.')

    # non-circular movers: the perception stack fits circles, so this is the
    # only scenario that can tell whether the multi-disc covering earns its keep
    write('shapes',
          ob('dyn_obs_1', (1.2, 1.8), (7.6, 1.8), 0.25) +
          ob('dyn_obs_2', (7.6, 6.8), (1.2, 6.8), 0.25),
          'A 0.7x0.4 box and a 1.2x0.3 cart, one each side of the divider. '
          'Circle fitting degenerates on a flat face and a single lidar view '
          'cannot see an object\'s depth, so this is where the covering discs '
          'are actually tested.')

    # stationary "mover" past the right gap
    write('parked',
          ob('dyn_obs_0', (RIGHT_GAP + 0.2, 5.4), (RIGHT_GAP + 0.2, 5.4), 0.0),
          'A stationary mover: tests the static/dynamic split directly.')
    print('\nvalidate: python3 evaluation/check_arena.py')


if __name__ == '__main__':
    main()
